/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafx;

import javafx.scene.paint.Color;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.VBox;
import javafx.scene.layout.HBox;
import javafx.scene.control.ScrollPane;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundFill;
import javafx.scene.layout.CornerRadii;
import javafx.geometry.Insets;
import java.text.SimpleDateFormat;  
import javafx.scene.text.Font;
import javafx.scene.layout.Region;

public class App extends Application {
    @Override
    public void start(Stage stage) {
        TrainList trainList = new TrainList("Stoke Newington");

        Font font = Font.loadFont("file:resources/fonts/NJFont-Book.ttf", 12);
        Font boldFont = Font.loadFont("file:resources/fonts/NJFont-BookBold.ttf", 12);

        VBox vbox = new VBox();
        vbox.setPrefWidth(640);
        
        for (int i = 0; i < trainList.trains.size(); i++) {
            Train element = trainList.trains.get(i);
            String arrivalTimeStr = new SimpleDateFormat("HH:mm").format(element.arrivalTime);
            Text arrivalTime = new Text(arrivalTimeStr);
            arrivalTime.setFont(boldFont);
            Text destinationName = new Text(element.destination);
            destinationName.setFont(font);
            Region spacer = new Region();
            spacer.setMinWidth(10);

            HBox row = new HBox(arrivalTime, spacer, destinationName);
            row.setPadding(new Insets(15, 12, 15, 12));
            row.setBackground(new Background(new BackgroundFill(Color.WHITE, new CornerRadii(10.0), Insets.EMPTY)));
            vbox.getChildren().addAll(row);
            vbox.setMargin(row, new Insets(10, 10, 10, 10));
        }

        ScrollPane scroll = new ScrollPane();
        scroll.setContent(vbox);
        Scene scene = new Scene(scroll, 640, 480);
        stage.setScene(scene);
        vbox.prefWidthProperty().bind(stage.widthProperty().multiply(0.9));
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}
