/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafx;

import javafx.scene.paint.Color;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.VBox;
import javafx.scene.layout.HBox;
import javafx.scene.control.ScrollPane;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundFill;
import javafx.scene.layout.CornerRadii;
import javafx.geometry.Insets;
import java.text.SimpleDateFormat;  
import javafx.scene.text.Font;
import javafx.scene.layout.Region;
import javafx.scene.control.Button;

public class App extends Application {
    public Scene trainDetailsView(Stage stage, Train train) {
        VBox vbox = new VBox();

        Button homeButton = new Button("Return home");
        homeButton.setOnAction(e -> {
            stage.setScene(mainView(stage));
        });

        Text destinationName = new Text(train.destination);

        vbox.getChildren().addAll(homeButton, destinationName);
        Scene scene = new Scene(vbox, 640, 480);
        return scene;
    }

    public Scene mainView(Stage stage) {
        TrainList trainList = new TrainList("Stoke Newington");

        Font font = Font.loadFont("file:resources/fonts/NJFont-Book.ttf", 12);
        Font boldFont = Font.loadFont("file:resources/fonts/NJFont-BookBold.ttf", 12);

        VBox vbox = new VBox();
        vbox.setPrefWidth(640);
        
        for (int i = 0; i < trainList.trains.size(); i++) {
            Train element = trainList.trains.get(i);
            String arrivalTimeStr = new SimpleDateFormat("HH:mm").format(element.arrivalTime);
            Text arrivalTime = new Text(arrivalTimeStr);
            arrivalTime.setFont(boldFont);
            Text destinationName = new Text(element.destination);
            destinationName.setFont(font);
            Region spacer = new Region();
            spacer.setMinWidth(10);

            Button trainButton = new Button("View details");
            trainButton.setOnAction(e -> {
                stage.setScene(trainDetailsView(stage, element));
            });

            HBox row = new HBox(arrivalTime, spacer, destinationName, trainButton);
            row.setPadding(new Insets(15, 12, 15, 12));
            row.setBackground(new Background(new BackgroundFill(Color.WHITE, new CornerRadii(10.0), Insets.EMPTY)));
            vbox.getChildren().addAll(row);
            vbox.setMargin(row, new Insets(10, 10, 10, 10));
        }

        ScrollPane scroll = new ScrollPane();
        scroll.setContent(vbox);
        vbox.prefWidthProperty().bind(stage.widthProperty().multiply(0.9));
        return new Scene(scroll, 640, 480);
    }

    @Override
    public void start(Stage stage) {
        Scene scene = mainView(stage);
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}
